# Generated by Django 2.2 on 2021-12-21 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
